#!/bin/bash
# =========================================================================== #
#            MIT License Copyright (c) 2022 Kris Nóva <kris@nivenly.com>      #
#                                                                             #
#                 ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                 #
#                 ┃   ███╗   ██╗ ██████╗ ██╗   ██╗ █████╗   ┃                 #
#                 ┃   ████╗  ██║██╔═████╗██║   ██║██╔══██╗  ┃                 #
#                 ┃   ██╔██╗ ██║██║██╔██║██║   ██║███████║  ┃                 #
#                 ┃   ██║╚██╗██║████╔╝██║╚██╗ ██╔╝██╔══██║  ┃                 #
#                 ┃   ██║ ╚████║╚██████╔╝ ╚████╔╝ ██║  ██║  ┃                 #
#                 ┃   ╚═╝  ╚═══╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝  ┃                 #
#                 ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                 #
#                                                                             #
#                        This machine kills fascists.                         #
#                                                                             #
# =========================================================================== #

# Curl all of the Twitter subdomains from dnsdumpster.com

echo "Checking Twitter.com bruh..."


## Note:
## To scrape the date please replace my command with your own version.
## You can find the command by going to dnsdumpster.com and running
## a query against twitter.com
## Right click > Inspect > Network > dnsdumpster.com > copy > copy as cURL
##
REFRESH=0
if [ "$REFRESH" -eq "1" ]; then
  echo "Running data refresh..."
  RAW_DUMP=$(curl 'https://dnsdumpster.com/' \
    -H 'authority: dnsdumpster.com' \
    -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8' \
    -H 'accept-language: en-US,en;q=0.8' \
    -H 'cache-control: max-age=0' \
    -H 'content-type: application/x-www-form-urlencoded' \
    -H 'cookie: csrftoken=fyYte1aBw8lTZo84u2G3wJR9cLlp2Shhy5uaB8QOHZC2IlF1jMIHcd83od6Z7kak' \
    -H 'origin: https://dnsdumpster.com' \
    -H 'referer: https://dnsdumpster.com/' \
    -H 'sec-fetch-dest: document' \
    -H 'sec-fetch-mode: navigate' \
    -H 'sec-fetch-site: same-origin' \
    -H 'sec-fetch-user: ?1' \
    -H 'sec-gpc: 1' \
    -H 'upgrade-insecure-requests: 1' \
    -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
    --data-raw 'csrfmiddlewaretoken=mjuId8jdKpOX1Jw5B5bOr2Hh2PHo27VcFQ0pAfZqVg56KG32qPds7wYbehsY7zOf&targetip=twitter.com&user=free' \
    --compressed)
   $RAW_DUMP > out/twitter.dns.dump
fi

# IPs Online
cat out/twitter.dns.dump | htmlq '.col-md-3' | cut -d ">" -f 2 | cut -d "<" -f 1 | uniq | sort | grep "\." > out/twitter.ips
IPS_COUNT=$(cat out/twitter.ips | wc -l)
echo "Found $IPS_COUNT IP addresses to check..."

# Subdomains Online
cat out/twitter.dns.dump | htmlq '.col-md-3' | cut -d ">" -f 4 | cut -d "<" -f 1 | sort | uniq | grep -v "United States" > out/twitter.subdomains
SUBDOMAINS_COUNT=$(cat out/twitter.subdomains | wc -l)
echo "Found $SUBDOMAINS_COUNT subdomains to check..."

SUBS=$(cat out/twitter.subdomains)
for sub in $SUBS; do
  ./scan-domain $sub
done


